import { UserProvider } from "../contexts/UserContext"
import '../styles/globals.css';

export const metadata = {
  title: 'Login e Cadastro',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          {children}
        </UserProvider>
      </body>
    </html>
  )
}
